name: quick-check
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  workflow_dispatch:
env:
  project-name: 2PPy
  workflow: quick-check
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        run: | 
          python --version
          pip --version
          java --version
          javac --version

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history

      - name: Restore Python dependencies
        run: pip install -r requirements.txt

      - name: Restore JVM dependencies
        run: ./download-jars.sh

      - name: Test
        run: python -m unittest
