name: quick-check
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
env:
  # jdk-version: openjdk@~1.15.0
  project-name: 2PPy
  workflow: quick-check
  # gradle-options: "--no-daemon --console=plain --stacktrace"
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        run: | 
          python --version
          pip --version
          java --version
          javac --version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all history

      # - name: Get All Tags
      #   run: git fetch --tags -f

      - name: Restore Python dependencies
        run: pip install -r requirements.txt

      - name: Restore JVM dependencies
        run: ./download-jars.sh

      - name: Test
        run: python -m unittest
